#include <pebble.h>
void send(int seq, int key1, int value1, int key2, int value2);
//#define DEBUG APP_LOG(APP_LOG_LEVEL_DEBUG,
#if !PBL_PLATFORM_CHALK
#define SCREEN_WIDTH 144
#define SCREEN_HEIGHT 168
#else
#define SCREEN_WIDTH 180
#define SCREEN_HEIGHT 180
#endif

#define VERSION 1
#define INBOUND_SIZE 128
#if !PBL_COLOR
#define OUTBOUND_SIZE 64
#else
#define OUTBOUND_SIZE 256
#endif
#define MAX_DIALOGS 10
#define DIALOGS_TITLE_MAX_LENGTH 100
#define DIALOGS_TEXT_MAX_LENGTH 100

#define MAX_MESSAGES 10
#define TIME_MAX_LENGTH 10
#define MESSAGES_TEXT_MAX_LENGTH 2000

#define MAX_ANSWERS 10
#define ANSWERS_MAX_LENGTH 100

#define PAGE_DIALOGS 0
#define PAGE_MESSAGES 1
#define PAGE_ANSWERS 2
#define PAGE_NOTIFICATIONS 3

#define MSG_KEY_SEQ 0
#define MSG_KEY_STATE 1
#define MSG_KEY_CRITICAL_ERROR 2
#define MSG_KEY_VK_ERROR 3
#define MSG_KEY_DIALOGS_START 4
#define MSG_KEY_DIALOG_ID 5
#define MSG_KEY_DIALOG_TITLE 6
#define MSG_KEY_DIALOG_TEXT 7
#define MSG_KEY_DIALOG_END 8
#define MSG_KEY_DIALOG_OUT 9
#define MSG_KEY_MESSAGES_START 10
#define MSG_KEY_MESSAGES_NAME 11
#define MSG_KEY_MESSAGES_OUT 12
#define MSG_KEY_MESSAGES_TEXT 13
#define MSG_KEY_MESSAGES_DATE 14
#define MSG_KEY_MESSAGES_ATTACHMENTS 15
#define MSG_KEY_MESSAGES_READ 16
#define MSG_KEY_MESSAGES_END 17
#define MSG_KEY_REQUEST 18
#define MSG_KEY_REQUEST_LIST 19
#define MSG_KEY_ANSWERS_START 20
#define MSG_KEY_ANSWERS_ELEMENT 21
#define MSG_KEY_ANSWERS_END 22
#define MSG_KEY_ANSWER_TO 23
#define MSG_KEY_ANSWER_MESSAGE 24
#define MSG_KEY_REFRESH_DIALOGS 25
#define MSG_KEY_SHOW_NOTIFICATIONS 26
#define MSG_KEY_NOTIFICATIONS_START 27
#define MSG_KEY_NOTIFICATIONS_TEXT 30
#define MSG_KEY_NOTIFICATIONS_TEXT_END 31
#define MSG_KEY_NOTIFICATIONS_END 33
#define MSG_KEY_JAVASCRIPT_STARTED 35
#define MSG_KEY_ANSWER_MESSAGE_CUSTOM 36

#define STATE_REQUEST 1
#define STATE_RECEIVING 2